# Generated by Django 6.1.1 on 2026-09-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodels",
            name="base_urls",
            field=models.ManyToManyField(
                blank=True, related_name="ai_configs", to="agents.aibaseurl", verbose_name="关联的Base URL"
            ),
        ),
        migrations.RenameModel(
            old_name="AiBaseUrl",
            new_name="AIPlatform",
        ),
        migrations.CreateModel(
            name="AiApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                ("api_key", models.CharField(max_length=500, verbose_name="API Key")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="agents.aiplatform",
                        verbose_name="所属平台",
                    ),
                ),
            ],
        ),
    ]
