# Generated by Django 6.1.1 on 2026-09-26 08:10

from django.db import migrations, models


def copy_api_keys_to_platform(apps, schema_editor):
    """删除 AiApiKey 表前，把各平台最新一条 Key 搬到 AIPlatform.api_key"""
    AIPlatform = apps.get_model("agents", "AIPlatform")
    for platform in AIPlatform.objects.all():
        key = platform.api_keys.order_by("-id").first()
        if key:
            platform.api_key = key.api_key
            platform.save(update_fields=["api_key"])


def copy_api_keys_back(apps, schema_editor):
    """回滚：依据平台上的 Key 重建 AiApiKey 记录"""
    AIPlatform = apps.get_model("agents", "AIPlatform")
    AiApiKey = apps.get_model("agents", "AiApiKey")
    for platform in AIPlatform.objects.exclude(api_key=""):
        AiApiKey.objects.create(name=platform.name, api_key=platform.api_key, platform=platform, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_aimodels_base_urls_rename_aibaseurl_aiplatform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiplatform",
            name="api_key",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="API Key"),
        ),
        migrations.RunPython(copy_api_keys_to_platform, copy_api_keys_back),
        migrations.DeleteModel(
            name="AiApiKey",
        ),
    ]
